### ISSUE TITLE
mvnw clean package fails with FileNotFoundException

### ISSUE THREAD

**Issue by ngokavar** [cicsdev/cics-java-liberty-springboot-jdbc#3]
./mvnw clean package
Exception in thread "main" java.io.FileNotFoundException: https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.5/apache-maven-3.6.5-bin.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.apache.maven.wrapper.DefaultDownloader.downloadInternal(DefaultDownloader.java:90)
	at org.apache.maven.wrapper.DefaultDownloader.download(DefaultDownloader.java:76)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:72)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
==

Updating the .mvn/wrapper/maven-wrapper.properties with distributionUrl pointing to 3.6.3 solved the issue.
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.3/apache-maven-3.6.3-bin.zip

**Comment by IvanHargreaves** [comment]
Got spot. Fixed now. Thanks.
